### ISSUE TITLE
What access permissions are necessary for login with token?

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#6]
I'd like to try this mini program but I'm not sure what access permissions should I give when creating a new token https://github.com/settings/tokens/new.
All checked seems to be overkill.

My guess is:

* Repo: all
* user: all
* notification: all

But looks like it's not enough, at least the issue list is not displayed normally; only several outdated issues are listed. -- not sure if this is a bug or caused by wrong token settings.

**Comment by kezhenxu94** [comment]
> I'd like to try this mini program but I'm not sure what access permissions should I give when creating a new token https://github.com/settings/tokens/new.
> All checked seems to be overkill.
> 
> My guess is:
> 
> * Repo: all
> * user: all
> * notification: all
> 
> But looks like it's not enough, at least the issue list is not displayed normally; only several outdated issues are listed. -- not sure if this is a bug or caused by wrong token settings.

Thanks for your interest in this project, I think your guess is right and the listed scopes are enough, I believe it's a bug here, thanks for reporting this, I'll try to fix it in the next version :)

**Comment by kezhenxu94** [comment]
Hi @johnnychen94 I've just fixed this bug and submitted to WeChat for review, it should be available tomorrow :) I've also added a feature that shows contributors in repository detail page, please give it a try tomorrow and feel free to feed back here, thanks :)

![image](https://user-images.githubusercontent.com/15965696/55890559-8051e580-5be5-11e9-88b9-e01533a34dde.png)

**Comment by kezhenxu94** [comment]
Hi @johnnychen94 , the new version that fixes this bug is released just now, please give it a try, if it doesn't work, please make sure exit the mini program **completely** and restart, thanks again for reporting this. I'm closing this for now

**Comment by johnnychen94** [comment]
Looks like it still doesn't work.

I've deleted this mini-program and rescanned the QR code to open it. -- I guess this means "exit the mini program **completely and restart**"
I've also regenerated an all-permitted token to login. -- this issue is not related to limited token permission.

Perhaps it's just because of a server-side update delay, I'll check it later today. @kezhenxu94 

I can provide more information if you need.

![image](https://user-images.githubusercontent.com/8684355/55924108-0d735980-5c3b-11e9-9409-3a9395596573.png)

**Comment by kezhenxu94** [comment]
That's weird, if it still doesn't work, feel free to reopen this issue
